[package]
name = "sports_record"
version = "0.1.0"
authors = ["Evan Merlock <vnmrlck@gmail.com>"]

[dependencies]
iron = "0.5.1"
router = "0.5.0"
uuid = { version = "0.2", features = ["v4"] }
rusqlite = "0.10.1"
scoped_threadpool = "0.1.7"